### ISSUE TITLE
Degit vs template repository

### ISSUE THREAD

**Issue by MartinKavik** [fattenap/seed-quickstart#1]
See https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template.
=> You can mark the repository as a template and then users can click on a big green button instead of "degitting".
Just tip, feel free to close the issue.

**Comment by fattenap** [comment]
Hi,

Yes I thought about that, but it seems that the user is required to have a github account and it creates a repo for them. degit allows more flexibility if the user wanted to use gitLab or BitBucket. I might add it in but explain how it works. Please correct me if my assumption is incorrect.

Thanks
Frank

**Comment by fattenap** [comment]
Hi,

I decided to take your advice and went with the Template.

Thanks
Frank
