### ISSUE TITLE
seed-quickstart vs seed-quickstart-webpack

### ISSUE THREAD

**Issue by MartinKavik** [fattenap/seed-quickstart#2]
> webpack, wasm pack, tailwindcss and auto-reload

What's the difference between this QS and https://github.com/seed-rs/seed-quickstart-webpack?
Maybe it would be nice to write a comparison / purpose of this QS to README so users can decide which QS to use.

**Comment by fattenap** [comment]
Yeah, you're right. I took another look at your quick start and it's very good. Probably, best if I remove this from the awesome list to avoid confusion. Sorry to mess you about.

Thanks

**Comment by MartinKavik** [comment]
I'll update both quickstarts (the Rust one and the webpack one) in next days and then I plan to move to [Seeder](https://github.com/MartinKavik/seeder).

So.. if your quickstart is starting to look like Seed official webpack quickstart and we probably don't want to maintain two similar quickstarts.. maybe you will be interested in maintaining Seed's webpack quickstart?

**Comment by fattenap** [comment]
Sure, that sounds good.

**Comment by MartinKavik** [comment]
@fattenap Nice! I'll start with Webpack quickstart updating. Once done, I'll try to not forget to notify you and add needed permissions for you. Thanks!

**Comment by MartinKavik** [comment]
@fattenap Webpack quickstart updated and I've sent you invitations. Please remove the link from Awesome list when you decide to archive this repo.
